development:
  adapter: postgresql
  encoding: unicode
  database: athenaeum
  pool: 5
  username: rails
  password: railsapp

test:
  adapter: postgresql
  encoding: unicode
  database: athenaeum_testing
  pool: 5
  username: rails
  password: railsapp